# Generated by Django 3.2.12 on 2023-11-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_answer',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='New Chat', max_length=50),
        ),
    ]
