# Generated by Django 3.2.12 on 2023-11-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20231122_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='preview',
            field=models.TextField(default='How can I assist you today?', max_length=50),
        ),
        migrations.AlterField(
            model_name='bot',
            name='prompt',
            field=models.TextField(default="I'm a helpful assistant.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='New Chat', max_length=30),
        ),
    ]
