# Generated by Django 3.2.12 on 2023-11-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20231122_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='previous_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.message'),
        ),
    ]
