# Generated by Narges 3.2.12 on 2023-11-23 11:27

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_message_previous_message'),
    ]

    operations = [
        VectorExtension()
    ]
